# Query 1 # Retrieve all QTL (select) with Trait ontology containing value panicle

BASE <http://www.southgreen.fr/agrold/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab:<vocabulary/>
SELECT distinct ?QTL ?Label ?trait_label ?chr
 WHERE {
        ?QTL a <http://www.w3.org/2002/07/owl#Class>;
             rdfs:subClassOf <http://purl.obolibrary.org/obo/SO_0000771>;
             rdfs:label ?Label;
             vocab:is_located_on ?chr;
             vocab:has_start_position ?start;
             vocab:has_end_position ?end;
             vocab:has_trait ?trait.
  		?trait rdfs:label ?trait_label.
  FILTER(REGEX(str(?trait_label), "panicle"))
  FILTER((?chr="4"))
  FILTER(xsd:integer(?start) <= 31000000 && xsd:integer(?end)>=31500000)
  
}


# Query 2 # Retrieve all genes (select) with Trait ontology containing value panicle = 1 result
BASE <http://www.southgreen.fr/agrold/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab: <vocabulary/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX obo:<http://purl.obolibrary.org/obo/>
PREFIX tax:<http://identifiers.org/taxonomy/>
SELECT DISTINCT ?gene ?label ?start ?chromosome ?chromosome_nb ?nb
 WHERE{
 ?gene rdf:type vocab:Gene.
 OPTIONAL {
    ?gene rdfs:label ?label.}
 ?gene faldo:location ?chromosome .
 ?gene obo:RO_0002162 tax:39947 .
 ?chromosome faldo:reference ?chromosome_nb.
 ?chromosome faldo:begin ?start_uri.
 ?start_uri faldo:position ?start.
 ?gene <http://purl.org/dc/elements/1.1/description> ?description.
 #bind(xsd:int(?start) as ?startInt)
 FILTER(?start >= 31000000 && ?start <= 31500000).
 BIND(REPLACE(str(?chromosome_nb), '.*/(\\d+)$', "$1") as ?nb ).
FILTER(xsd:int(?nb) = 4 )
 FILTER(REGEX(str(?description),"panicle"))
}


# Query 3 # Retrieve all genes (select) with Trait ontology containing value panicle = 81 results
BASE <http://www.southgreen.fr/agrold/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab: <vocabulary/>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX obo:<http://purl.obolibrary.org/obo/>
PREFIX tax:<http://identifiers.org/taxonomy/>
SELECT DISTINCT ?gene ?label ?start ?chromosome ?chromosome_nb ?nb
 WHERE{
 ?gene rdf:type vocab:Gene.
 OPTIONAL {
    ?gene rdfs:label ?label.}
 ?gene faldo:location ?chromosome .
 ?gene obo:RO_0002162 tax:39947 .
 ?chromosome faldo:reference ?chromosome_nb.
 ?chromosome faldo:begin ?start_uri.
 ?start_uri faldo:position ?start.
 #?gene <http://purl.org/dc/elements/1.1/description> ?description.
 #bind(xsd:int(?start) as ?startInt)
 FILTER(?start >= 31000000 && ?start <= 31500000).
 BIND(REPLACE(str(?chromosome_nb), '.*/(\\d+)$', "$1") as ?nb ).
FILTER(xsd:int(?nb) = 4 )
# FILTER(REGEX(str(?description),"panicle"))
}
